# Generated by Django 5.2.3 on 2025-06-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('plataforma', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=30)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
